import { useMemo } from 'react';
import { cn } from '@/lib/utils';

/**
 * Renders the markdown the backend report builder produces.
 *
 * Deliberately a small, closed renderer rather than a markdown library: the
 * input is generated by `report.py` and uses a known, fixed subset — headings,
 * bullets, tables, bold and inline code. Nothing here interprets raw HTML, so
 * source text quoted from a case record cannot inject markup.
 */

function renderInline(text, keyPrefix) {
  const parts = [];
  // Split on **bold** and `code`, keeping the delimiters.
  const tokens = String(text).split(/(\*\*[^*]+\*\*|`[^`]+`)/g);
  tokens.forEach((token, i) => {
    if (!token) return;
    const key = `${keyPrefix}-${i}`;
    if (token.startsWith('**') && token.endsWith('**') && token.length > 4) {
      parts.push(
        <strong key={key} className="font-semibold text-navy-900">
          {token.slice(2, -2)}
        </strong>
      );
    } else if (token.startsWith('`') && token.endsWith('`') && token.length > 2) {
      parts.push(
        <code key={key} className="rounded bg-slate-100 px-1 py-0.5 font-mono text-[12px] text-navy-700">
          {token.slice(1, -1)}
        </code>
      );
    } else {
      parts.push(<span key={key}>{token}</span>);
    }
  });
  return parts;
}

function splitRow(line) {
  return line
    .replace(/^\||\|$/g, '')
    .split('|')
    .map((c) => c.trim());
}

function isSeparatorRow(line) {
  return /^\|?[\s:|-]+\|[\s:|-]*$/.test(line) && line.includes('-');
}

function parse(markdown) {
  const lines = String(markdown || '').split('\n');
  const blocks = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    if (!line.trim()) {
      i += 1;
      continue;
    }

    // Table: a header row, a separator row, then body rows.
    if (line.trim().startsWith('|') && isSeparatorRow(lines[i + 1] || '')) {
      const header = splitRow(line);
      const rows = [];
      i += 2;
      while (i < lines.length && lines[i].trim().startsWith('|')) {
        rows.push(splitRow(lines[i]));
        i += 1;
      }
      blocks.push({ kind: 'table', header, rows });
      continue;
    }

    const heading = line.match(/^(#{1,4})\s+(.*)$/);
    if (heading) {
      blocks.push({ kind: 'heading', level: heading[1].length, text: heading[2] });
      i += 1;
      continue;
    }

    if (/^\s*[-*]\s+/.test(line)) {
      const items = [];
      while (i < lines.length && /^\s*[-*]\s+/.test(lines[i])) {
        items.push(lines[i].replace(/^\s*[-*]\s+/, ''));
        i += 1;
      }
      blocks.push({ kind: 'list', items });
      continue;
    }

    // Paragraph: consume until a blank line or the start of another block.
    const para = [];
    while (
      i < lines.length &&
      lines[i].trim() &&
      !/^(#{1,4})\s/.test(lines[i]) &&
      !/^\s*[-*]\s+/.test(lines[i]) &&
      !lines[i].trim().startsWith('|')
    ) {
      para.push(lines[i].trim());
      i += 1;
    }
    if (para.length) blocks.push({ kind: 'paragraph', text: para.join(' ') });
  }

  return blocks;
}

const HEADING_CLASS = {
  1: 'text-base font-semibold text-navy-900',
  2: 'text-sm font-semibold text-navy-900',
  3: 'text-[13px] font-semibold text-navy-800',
  4: 'text-[13px] font-semibold text-navy-700',
};

export function MarkdownReport({ markdown, className }) {
  const blocks = useMemo(() => parse(markdown), [markdown]);

  if (!blocks.length) {
    return <p className={cn('text-[13px] text-navy-400', className)}>No summary was produced.</p>;
  }

  return (
    <div className={cn('space-y-3.5', className)}>
      {blocks.map((block, bi) => {
        if (block.kind === 'heading') {
          return (
            <h3 key={bi} className={cn(HEADING_CLASS[block.level] || HEADING_CLASS[3], bi > 0 && 'pt-1')}>
              {renderInline(block.text, `h${bi}`)}
            </h3>
          );
        }
        if (block.kind === 'list') {
          return (
            <ul key={bi} className="space-y-1.5">
              {block.items.map((item, ii) => (
                <li key={ii} className="flex gap-2 text-[13px] leading-relaxed text-navy-600">
                  <span className="mt-[7px] h-1 w-1 shrink-0 rounded-full bg-teal-500" aria-hidden />
                  <span>{renderInline(item, `l${bi}-${ii}`)}</span>
                </li>
              ))}
            </ul>
          );
        }
        if (block.kind === 'table') {
          return (
            <div key={bi} className="w-full overflow-x-auto rounded-lg border border-slate-200">
              <table className="w-full border-collapse text-left text-[13px]">
                <thead>
                  <tr>
                    {block.header.map((h, hi) => (
                      <th
                        key={hi}
                        className="border-b border-slate-200 bg-slate-50/80 px-3 py-2 text-[11px] font-semibold uppercase tracking-wide text-navy-400"
                      >
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {block.rows.map((row, ri) => (
                    <tr key={ri}>
                      {row.map((cell, ci) => (
                        <td key={ci} className="px-3 py-2 align-top text-navy-700">
                          {renderInline(cell, `t${bi}-${ri}-${ci}`)}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          );
        }
        return (
          <p key={bi} className="text-[13px] leading-relaxed text-navy-600">
            {renderInline(block.text, `p${bi}`)}
          </p>
        );
      })}
    </div>
  );
}
